name: Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Installation
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm install
      - name: Lint
        run: npm run lint

  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Installation
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm install
      - name: Test
        run: npm run build && npm test

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"] # https://aka.ms/codeql-docs/language-support
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v2
        with: # https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@v2
      - uses: github/codeql-action/analyze@v2
